Repository block-wallet/extension, pull requests merged in 2022-10, with the labels that each got.

#147 style: adjust add networks search results spacing
  packages/ui/src/components/chain/ChainDisplay.tsx
  packages/ui/src/routes/networks/SearchNetworkPage.tsx
Labels: enhancement

#91 [Feat] Accessibility tags
  packages/ui/src/components/account/AccountMultipleSelect.tsx
  packages/ui/src/routes/dApp/TransactionConfirmPage.tsx
Labels: ui

#152 Style/improve network selector dropdown
  packages/ui/src/components/input/NetworkSelect.tsx
  packages/ui/src/routes/networks/NetworksPage.tsx
Labels: ui

#155 Fix/node validation
  packages/background/package.json
  packages/background/src/infrastructure/stores/migrator/migrations/index.ts
  packages/background/src/infrastructure/stores/migrator/migrations/migration-43.ts
  packages/background/src/infrastructure/stores/migrator/migrations/migration-44.ts
  packages/background/src/utils/constants/networks.ts
  packages/background/yarn.lock
  packages/ui/src/routes/networks/NetworkFormPage.tsx
Labels: bug, background, ui

#159 fix: my accounts tooltip text consistency
  packages/ui/src/assets/images/icons/accounts.svg
  packages/ui/src/components/account/AccountMenu.tsx
  packages/ui/src/routes/PopupPage.tsx
Labels: ui

#162 [Automated] Extension release v0.4.1
  package.json
  public/manifest.json
  release-notes.json
Labels: automated, release

#168 [Fix] Use imperative go back routes to avoid crash networks flow
  packages/ui/src/components/input/NetworkSelect.tsx
  packages/ui/src/routes/networks/NetworkFormPage.tsx
  packages/ui/src/routes/networks/NetworksPage.tsx
Labels: bug, ui

#171 Fix/delete network btn clickable area
  packages/ui/src/components/account/AccountDisplay.tsx
  packages/ui/src/components/account/AccountFilters.tsx
  packages/ui/src/components/assets/AssetDetailsPage.tsx
  packages/ui/src/components/chain/ChainFiltersButton.tsx
  packages/ui/src/components/ui/Dropdown/DropdownMenu.tsx
  packages/ui/src/routes/networks/NetworkFormPage.tsx
  packages/ui/src/routes/settings/ConnectedSiteAccountsPage.tsx
Labels: bug, ui

#173 UX/network indicator in send and swap flow
  packages/ui/src/components/popup/PopupHeader.tsx
  packages/ui/src/routes/send/SendConfirmPage.tsx
  packages/ui/src/routes/send/SendPage.tsx
  packages/ui/src/routes/swap/SwapConfirmPage.tsx
  packages/ui/src/routes/swap/SwapPage.tsx
Labels: enhancement, ui

#166 Feat/allow user to order networks
  packages/background/package.json
  packages/background/src/controllers/BlankController.ts
  packages/background/src/controllers/NetworkController.ts
  packages/background/src/infrastructure/stores/migrator/migrations/index.ts
  packages/background/src/infrastructure/stores/migrator/migrations/migration-45.ts
  packages/background/src/utils/constants/networks.ts
  packages/background/src/utils/networks.ts
  packages/background/src/utils/types/communication.ts
  packages/ui/package.json
  packages/ui/src/components/networks/NetworkDisplay.tsx
  packages/ui/src/context/commActions.ts
  packages/ui/src/context/commTypes.ts
  packages/ui/src/routes/networks/NetworksPage.tsx
  packages/ui/yarn.lock
Labels: enhancement, background, ui

#177 Feat/add custom token address validation
  packages/background/src/controllers/erc-20/TokenController.ts
  packages/background/src/controllers/erc-20/transactions/Transaction.ts
  packages/ui/src/components/input/TextInput.tsx
  packages/ui/src/components/token/AddTokenManualView.tsx
  packages/ui/src/routes/settings/AddTokensPage.tsx
Labels: enhancement, background, ui

#180 fix: lock tooltip placement
  packages/ui/src/routes/UnlockPage.tsx
Labels: bug, ui

#181 [Feat] Update Asset Balance
  packages/background/Makefile
  packages/background/src/controllers/AccountTrackerController.ts
  packages/background/src/controllers/erc-20/TokenController.ts
Labels: background
