Repository block-wallet/extension, pull requests merged in 2022-11, with the labels that each got.

#182 fix: big amount & token name glitch
  packages/ui/src/components/transactions/TransactionDetailsBasic.tsx
  packages/ui/src/components/transactions/TransactionItem.tsx
Labels: bug, ui

#192 [Feat] Add balance and asset Name on DisplayToken
  packages/ui/src/components/assets/AssetDetailsPage.tsx
  packages/ui/src/components/assets/AssetSelection.tsx
  packages/ui/src/components/token/AddTokenManualView.tsx
  packages/ui/src/components/token/TokenDisplay.tsx
  packages/ui/src/components/token/TokenLogo.tsx
Labels: ui

#194 Fix/dapp origin posible exploit
  packages/ui/src/routes/connect/ConnectPage.tsx
  packages/ui/src/routes/dApp/TransactionConfirmPage.tsx
  packages/ui/src/util/constants.ts
  packages/ui/src/util/isOriginSafe.ts
Labels: bug, enhancement, ui

#190 Feat/custom networks
  packages/background/src/controllers/BlankController.ts
  packages/background/src/controllers/NetworkController.ts
  packages/background/src/utils/constants/networks.ts
  packages/background/src/utils/ethereumChain.ts
  packages/background/src/utils/types/communication.ts
  packages/ui/src/components/chain/ChainFiltersButton.tsx
  packages/ui/src/components/chain/RPCValidationEndLabelInfo.tsx
  packages/ui/src/routes/networks/NetworkFormPage.tsx
  packages/ui/yarn.lock
Labels: enhancement, background, ui

#191 fix: networks sorting ux
  packages/ui/src/components/networks/NetworkDisplay.tsx
  packages/ui/src/routes/networks/NetworksPage.tsx
Labels: enhancement, ui

#205 fix: transaction message truncate width
  packages/ui/src/components/transactions/TransactionItem.tsx
Labels: bug, ui

#206 [Automated] Extension release v0.4.2
  package.json
  public/manifest.json
  release-notes.json
Labels: automated, release

#207 [Chore] UI sourcemaps
  Makefile
Labels: enhancement

#208 [Feat] Focus on amount input when clicking the blue square
  packages/ui/src/routes/bridge/BridgeSetupPage.tsx
Labels: enhancement, ui

#211 [Fix] SeedImport OnPaste vs OnChange
  packages/ui/src/components/setup/SeedImport.tsx
Labels: bug, ui

#198 Fix/approve asset page ux improvement
  packages/ui/src/assets/images/unknown_token.svg
  packages/ui/src/components/label/WarningTip.tsx
  packages/ui/src/routes/dApp/WatchAsset.tsx
Labels: bug, ui

#217 [Fix] Add network page misplaced tooltip
  packages/ui/src/routes/dApp/AddEthereumChain.tsx
Labels: bug, ui

#219 [Chore] Remove e2e in commits pipelines
  .github/workflows/ci.yml
  .github/workflows/skip_e2e.yml
Labels: workflow

#220 [Fix] zksync explorer
  packages/background/package.json
  packages/background/src/infrastructure/stores/migrator/migrations/index.ts
  packages/background/src/infrastructure/stores/migrator/migrations/migration-49.ts
  packages/background/src/infrastructure/stores/migrator/migrations/migration-50.ts
  packages/background/src/infrastructure/stores/migrator/migrations/migration-51.ts
  packages/background/src/utils/constants/networks.ts
Labels: bug, background

#216 [Feat] Switch Network after addition
  packages/background/src/controllers/BlankProviderController.ts
  packages/ui/src/components/chain/RPCValidationEndLabelInfo.tsx
  packages/ui/src/components/dialog/DetailsDialog.tsx
Labels: enhancement, background

#196 [Fix] Remove Null Address from recent addresses
  packages/background/src/controllers/AccountTrackerController.ts
  packages/background/src/controllers/AddressBookController.ts
  packages/background/src/controllers/BlankController.ts
  packages/background/src/controllers/BridgeController.ts
  packages/background/src/controllers/erc-20/TokenController.ts
  packages/background/src/controllers/erc-20/transactions/Transaction.ts
  packages/background/src/utils/token.ts
  packages/background/test/controllers/erc-20/TokenController.test.ts
  packages/background/test/utils/token.test.ts
  packages/ui/src/components/addressBook/AddressDisplay.tsx
  packages/ui/src/components/icons/ExclamationCircleIconFull.tsx
  packages/ui/src/components/transactions/TransactionDetailsBasic.tsx
  packages/ui/src/context/hooks/useAccountNameByAddress.ts
  packages/ui/src/routes/send/SendConfirmPage.tsx
  packages/ui/src/util/tokenUtils.ts
Labels: enhancement, ui

#225 [Automated] Extension release v0.5.0
  package.json
  public/manifest.json
  release-notes.json
Labels: automated, release

#215 [Feat] Loading skeleton
  packages/background/src/controllers/ExchangeRatesController.ts
  packages/background/src/utils/constants/initialState.ts
  packages/background/test/infrastructure/stores/migrator/reconciler.test.ts
  packages/background/test/mocks/mock-exchangerates.ts
  packages/ui/src/assets/images/icons/bluecircle_skeleton.json
  packages/ui/src/assets/images/icons/blueline_skeleton.json
  packages/ui/src/assets/images/icons/greycircle_skeleton.json
  packages/ui/src/assets/images/icons/greyline_skeleton.json
  packages/ui/src/components/AnimatedIcon.tsx
  packages/ui/src/components/AssetsList.tsx
  packages/ui/src/components/gas/GasPricesInfo.tsx
  packages/ui/src/components/input/NetworkSelect.tsx
  packages/ui/src/components/skeleton/AssetsLoadingSkeleton.tsx
  packages/ui/src/components/skeleton/BalanceLoadingSkeleton.tsx
  packages/ui/src/components/skeleton/TransactionsLoadingSkeleton.tsx
  packages/ui/src/components/token/TokenSummary.tsx
  packages/ui/src/components/transactions/TransactionsList.tsx
  packages/ui/src/mock/MockBackgroundState.tsx
  packages/ui/src/routes/PopupPage.tsx
Labels: enhancement, background, ui

#229 [Fix] Prevent clicks while loading
  packages/ui/src/components/input/NetworkSelect.tsx
  packages/ui/src/components/loading/TransparentOverlay.tsx
Labels: bug, ui

#231 [Fix] Case sensitive account name validation
  packages/ui/src/util/__tests__/account.test.ts
  packages/ui/src/util/account.ts
Labels: bug, ui

#241 [Fix] Non-clickable network change when provider down
  packages/ui/src/components/input/NetworkSelect.tsx
  packages/ui/src/components/loading/TransparentOverlay.tsx
  packages/ui/src/routes/PopupPage.tsx
Labels: bug, ui
